title: "Ahrar Bin Aslam"
description: "Cybersecurity Master's Student at Saarland University"
theme: jekyll-theme-minimal
author:
  name: "Ahrar Bin Aslam"
  email: "ahas00001@stud.uni-saarland.de"
  social:
    linkedin: "https://linkedin.com/in/ahrarbinaslam23"
    github: "https://github.com/ahrarbinaslam"
